### ISSUE TITLE
Deprecated warning: Space.getContentTypes

### ISSUE THREAD

**Issue by nuno-barreiro** [jugglingthebits/contentful-clean-space#4]
When running the tool to delete all content types, warning messages are being shown asking for the usage of the method Environment.getContentTypes to replace Space.getContentTypes due to the deprecation and future removal of the later.

**Comment by s5no5t** [comment]
Thanks for the info.
Do you think environment should be passed as a parameter, or that the tool should just delete all content types in all environments? Should it delete the environments as well?

**Comment by nuno-barreiro** [comment]
I think environment should be passed by parameter if possible. there might be the need to clean just a certain environment and maintain the rest as is. In this specific case I'm using I was cleaning up master so deleting it is not an option I could consider.

**Comment by s5no5t** [comment]
I have updated api usage so the warning is gone.
