### ISSUE TITLE
Using this tool is terrifying. Here's some ideas to make it less scary.

### ISSUE THREAD

**Issue by 0xStarcat** [jugglingthebits/contentful-clean-space#6]
Hi,

This is extremely helpful but terrifying to use.

My use case is that I have a sandbox environment I need to clear out which shares a space with the `master` environment of a production site for a commercial entity. 

This tool should provide more verbose feedback and change its default settings to make it less likely to accidentally the delete the `master` environment entries, which I am terrified might happen. 

Please implement the following:

1) Please do NOT make `master` the default value for the `--env` option, or set any default value here, please make the user set this manually every time.

2) Please DO make the default value for the `--yes` confirmation prompt `true` by default. 

3) Please DO print the environment name as a sanity check before deleting entries. 

4) Please DO provide an example of a "safe" and "correct" CLI command. So far, I have not been able to get the `--yes` flag to work correctly, having tried `--yes`, `--yes=true`, and `-y`. 

Thank you!

**Comment by s5no5t** [comment]
> Please do NOT make master the default value for the --env option, or set any default value here, please make the user set this manually every time.

This is implemented in `0.7.0`.

> Please DO make the default value for the --yes confirmation prompt true by default.

I'd like to understand why you're requesting this. IMO this currently aligns with the default behavior of many other cli tools that do potentially harmful things.

> Please DO print the environment name as a sanity check before deleting entries.

Implemented in `0.7.0`.

> Please DO provide an example of a "safe" and "correct" CLI command. So far, I have not been able to get the --yes flag to work correctly, having tried --yes, --yes=true, and -y.

I've added an example to the README.

Thank you for the feedback!

**Comment by 0xStarcat** [comment]
nice! thank you so much!
